name: neural-holography
channels:
  - pytorch
  - conda-forge
  - aotools
  - defaults
dependencies:

  - imageio=2.6.1

  - ninja=1.9.0
  - numba=0.51.2
  - numpy=1.16.4
  - pillow=6.0.0

  - protobuf=3.11.1
  - pycparser=2.19
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.1
  - pytorch=1.7.0=py3.7_cuda11.0.221_cudnn8.0.3_0
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.16.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - tensorboardx=1.9
  - tk=8.6.8
  - toolz=0.10.0
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.0.3
  - typing_extensions=3.7.4.3
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - cachetools==4.1.0
    - chardet==3.0.4
    - configargparse==1.0
    - densenet==0.1.1
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - importlib-metadata==1.6.0
    - markdown==3.2.2
    - oauthlib==3.1.0
    - opencv-python==4.4.0.42
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfirmata==1.1.0
    - pyserial==3.5
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - zipp==3.1.0
